### ISSUE TITLE
npm run dev仍然出现ant包依赖umi

### ISSUE THREAD

**Issue by Aaha0625** [gzgogo/antd-pro-mobx#1]
新手,麻烦看下有哪里没对没? 怎么还是出现了ant中的文件依赖了umi

ERROR in ./node_modules/ant-design-pro/lib/Authorized/AuthorizedRoute.js
Module not found: Error: Can't resolve 'umi' in '/home/hlbs/antd-pro-mobx-master/node_modules/ant-design-pro/lib/Authorized'
 @ ./node_modules/ant-design-pro/lib/Authorized/AuthorizedRoute.js 13:11-25
 @ ./node_modules/ant-design-pro/lib/Authorized/index.js
 @ ./node_modules/ant-design-pro/lib/index.js
 @ ./src/page/500/index.js
 @ ./src/layout/Root/index.js
 @ ./src/index.js
 @ multi @babel/polyfill ./src/index.js

**Comment by gzgogo** [comment]
问题已修复：这是由于antd-pro升级后，里面的AuthorizedRoute组件依赖了umi导致的，现在已经将antd版本临时降级到2.0.0。再有问题可以加我微信：459135899
